# Generated by Django 5.0 on 2023-12-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default=1, upload_to='book_covers/'),
            preserve_default=False,
        ),
    ]
