# Generated by Django 5.0 on 2023-12-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='book',
            field=models.CharField(max_length=50),
        ),
    ]
