# Generated by Django 5.0 on 2023-12-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_photo_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='books.book'),
        ),
    ]
